name = "murajun1978-dev-site"
type = "webpack"
account_id = ""
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"

[dev]
port=3000
ip="0.0.0.0"
